# Setup
title:               'Machine-Learning and Data-Science'
tagline:             ''
description:         ''
url:                 'https://alessandrosantospirito.github.io/documentations'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Alessandro Santospirito
  url:               
  email:             

# Gems
markdown: kramdown
plugins:
  - jekyll-paginate
include:
  - "public/_streamlit"

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
